#!/system/bin/sh
# Automatic EFS Backup by Kryten2k35
# Thanks to mcbyte_it for the interval

BACKUP_LOC=/sdcard/UltimaROM/EFS_Backup
LOG=$BACKUP_LOC/efs_backup.log
RUN_EVERY=172800
BUSYBOX=/system/xbin/busybox
CURRDATE=`date +%s`

if [ -e $LOG ]; then
    LASTRUN=`stat -t $LOG | awk '{print $14}'`
else
	touch $LOG
	busybox chmod 0775 $LOG
	LASTRUN=0
fi;

INTERVAL=$(expr $CURRDATE - $LASTRUN)

if [ INTERVAL -gt $RUN_EVERY ]; then

	if [ ! -d $BACKUP_LOC ]; then
		mkdir -p $BACKUP_LOC
		busybox chmod -R 0775 $BACKUP_LOC
	fi
	
    echo "EFS Backup started at $(date +"%m-%d-%y %H:%M:%S" )" | tee -a $LOG;

    $BUSYBOX tar zcvf $BACKUP_LOC/efs_$(date +%d%b%Y-%H%M).tar.gz /efs | tee -a $LOG;
	dd if=/dev/block/platform/dw_mmc/by-name/EFS of=$BACKUP_LOC/efs.img

    echo "EFS Backup ended at $(date +"%m-%d-%y %H:%M:%S" )" | tee -a $LOG;
fi;